project:
  type: website

website:
  title: "Stats Elevated"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: posts.qmd
    tools:
      - icon: github
        href: https://github.com/StatsElevated



